package org.dciss.app.model;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 13 16:17:57 CEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ComptesDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ComptesDefImpl() {
    }
}

