package org.dciss.app.model;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 18:40:01 CEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Employees9999CollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public Employees9999CollImpl() {
    }
}

