package org.dciss.app.model;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 01:47:34 CEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesDefImpl() {
    }
}

