package org.dciss.app.model;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 13 16:30:35 CEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StudentCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public StudentCollImpl() {
    }
}

